// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaK6Wp6DbJWOAiSMPOm4CZ2ajeRN9lXhk',
    appId: '1:526849381522:web:1dde87809961eebe9f424b',
    messagingSenderId: '526849381522',
    projectId: 'vaulty-8d608',
    authDomain: 'vaulty-8d608.firebaseapp.com',
    storageBucket: 'vaulty-8d608.firebasestorage.app',
    measurementId: 'G-B0XP14M577',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz_PNc2DItNn8eFwrUZ3Qp1PnTg9kVDU8',
    appId: '1:526849381522:android:acc9e2371fcdf24b9f424b',
    messagingSenderId: '526849381522',
    projectId: 'vaulty-8d608',
    storageBucket: 'vaulty-8d608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJrpYQ3Pqk2SBIqpnq683cJ5FaIMaAAGM',
    appId: '1:526849381522:ios:37a3a115aec7f5979f424b',
    messagingSenderId: '526849381522',
    projectId: 'vaulty-8d608',
    storageBucket: 'vaulty-8d608.firebasestorage.app',
    iosBundleId: 'com.example.vaulty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJrpYQ3Pqk2SBIqpnq683cJ5FaIMaAAGM',
    appId: '1:526849381522:ios:37a3a115aec7f5979f424b',
    messagingSenderId: '526849381522',
    projectId: 'vaulty-8d608',
    storageBucket: 'vaulty-8d608.firebasestorage.app',
    iosBundleId: 'com.example.vaulty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaK6Wp6DbJWOAiSMPOm4CZ2ajeRN9lXhk',
    appId: '1:526849381522:web:00b9db7df1f81fae9f424b',
    messagingSenderId: '526849381522',
    projectId: 'vaulty-8d608',
    authDomain: 'vaulty-8d608.firebaseapp.com',
    storageBucket: 'vaulty-8d608.firebasestorage.app',
    measurementId: 'G-HQWZBR4RTM',
  );
}
